version: "3.9"

services:
  djangoapp:
    container_name: djangoapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
        - static_volume:/app/backend/django_static
    entrypoint: /app/scripts/django.sh
    env_file:
      - .env
    depends_on:
      - db
      
  db:
    container_name: db
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data/

volumes:
    static_volume:
    postgres_data: